version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: install helm
        command: .circleci/install.sh
    - run:
        name: set env tag
        command: echo "export TAG=$(cat helm/reporting-processor-chart/Chart.yaml | grep version | awk '{ print $2 }')" >> $BASH_ENV
    - run:
        name: helm lint
        command: helm lint ./helm/reporting-processor-chart
    - run:
        name: docker login
        command: docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
    - run:
        name: docker build
        command: docker build -t quay.io/giantswarm/reporting-processor:${TAG} .

    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push quay.io/giantswarm/reporting-processor:${TAG}
          fi
