apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "processor.fullname" . }}
  
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: processor
            image: quay.io/giantswarm/reporting-processor:{{ .Chart.Version }}
            env:
            - name: ELASTICSEARCH_INDEX_URL_AGENT
              value: {{ .Values.elasticsearch_url }}/{{ .Values.agent_index }}
            - name: ELASTICSEARCH_INDEX_URL_PROCESSOR
              value: {{ .Values.elasticsearch_url }}/{{ .Values.index }}
